# Generated by Django 4.2.18 on 2025-01-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postpractice",
            name="player",
        ),
        migrations.RemoveField(
            model_name="prepractice",
            name="player",
        ),
    ]
