# Generated by Django 4.2.18 on 2025-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotions", models.TextField()),
                ("motivation", models.IntegerField()),
                ("focus", models.IntegerField()),
                ("managing_emotions", models.IntegerField()),
                ("satisfaction", models.IntegerField()),
                ("improvement", models.IntegerField()),
                ("happy", models.TextField()),
                ("experiences", models.TextField()),
                ("skills", models.TextField()),
                ("done_better", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
