# Generated by Django 4.2.18 on 2025-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_playerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepractice",
            name="drills",
            field=models.ManyToManyField(to="api.drill"),
        ),
    ]
